FC = gfortran
OMPFLAG = -fopenmp
FFLAGS = $(OMPFLAG) -g -O0
GPTL = /home/rosinski/gptl_v5.4.5
PAPI = /usr/lib/x86_64-linux-gnu
OBJS = main.o sub.o

%.o: %.F90
	$(FC) -c $(FFLAGS) -I$(GPTL) $<

a.out: $(OBJS)
	$(FC) -o $@ $(FFLAGS) $^ -L$(GPTL) -lgptl -L$(PAPI) -lpapi

clean:
	$(RM) *.o a.out
