CC        = nvc
CFLAGS    = -g
CACCFLAGS = -g -O0 -acc -Minfo=accel -m64 -Mcuda=cc61

FC        = nvfortran
FACCFLAGS = -g -O0 -acc -Minfo=accel -m64 -Mcuda=cc61

NVCC      = nvcc
CUFLAGS   = -gencode arch=compute_61,code=compute_61 -g -lineinfo -src-in-ptx -ftz=true -rdc=true

LIBNAME      = gptl
LIBNAME_CUDA = gptl_cuda
